### ISSUE TITLE
Java error occurs in MPLAB X when using auto complete

### ISSUE THREAD

**Issue by mellexpro** [mc6pac/toolchainCC8E#1]
MPLAB X version: 5.20
CC8E Version: 1.6F
OS: Windows 10

@mc6pac

When typing in the editor in  MPLAB X the symbolic auto complete does not function, the pop-up window just says "please wait...".

in the notifications section there is an error message with regards to a JAVA exception:

`java.lang.NoSuchMethodError: com.microchip.mplab.nbide.toolchainCommon.LTUtils.pathToBin(Lorg/netbeans/spi/project/ProjectConfiguration;)Ljava/lang/String;
	at com.github.mc6pac.toolchainCC8E.CC8ESystemIncludeProvider.getIncludes(Unknown Source)
	at com.microchip.mplab.nbide.embedded.api.Compiler.getSystemIncludeDirectories(Compiler.java:159)
	at com.microchip.mplab.nbide.embedded.makeproject.api.configurations.Item.getSystemIncludePaths(Item.java:942)
	at com.microchip.mplab.nbide.embedded.makeproject.api.configurations.Item.getSystemIncludePaths(Item.java:916)
	at org.netbeans.modules.cnd.modelimpl.csm.core.ProjectBase.getIncludeHandler(ProjectBase.java:1582)
	at org.netbeans.modules.cnd.modelimpl.csm.core.ProjectBase.createPreprocHandler(ProjectBase.java:1567)
	at org.netbeans.modules.cnd.modelimpl.csm.core.ProjectBase.findFileByItem(ProjectBase.java:2755)
	at org.netbeans.modules.cnd.modelimpl.csm.core.ProjectBase.findFile(ProjectBase.java:2697)
	at org.netbeans.modules.cnd.modelutil.CsmUtilities.getCsmFiles(CsmUtilities.java:483)
	at org.netbeans.modules.cnd.modelutil.CsmUtilities.getCsmFile(CsmUtilities.java:545)
	at org.netbeans.modules.cnd.modelutil.CsmUtilities.getCsmFile(CsmUtilities.java:356)
	at org.netbeans.modules.cnd.completion.cplusplus.NbCsmCompletionQuery.getCsmFile(NbCsmCompletionQuery.java:131)
	at org.netbeans.modules.cnd.completion.cplusplus.ext.CsmCompletionQuery.queryImpl(CsmCompletionQuery.java:537)
	at org.netbeans.modules.cnd.completion.cplusplus.ext.CsmCompletionQuery.query(CsmCompletionQuery.java:508)
	at org.netbeans.modules.cnd.completion.cplusplus.ext.CsmCompletionQuery.query(CsmCompletionQuery.java:501)
	at org.netbeans.modules.cnd.completion.cplusplus.ext.CsmCompletionQuery.query(CsmCompletionQuery.java:234)
	at org.netbeans.modules.cnd.completion.cplusplus.ext.CsmCompletionQuery.query(CsmCompletionQuery.java:213)
	at org.netbeans.modules.cnd.completion.cplusplus.CsmCompletionProvider$Query.query(CsmCompletionProvider.java:282)
	at org.netbeans.spi.editor.completion.support.AsyncCompletionTask.run(AsyncCompletionTask.java:223)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
`

this happens on the CC5X plugin as well.

Regards.

**Comment by mc6pac** [comment]
I have investigated a bit, and it looks like Microchip changed something about how their API works, without notifing 3rd party developers. Not sure when.m but i looks like all 5.xx versions are affected. Have not tested 4xx yet.

**Comment by mc6pac** [comment]
From whar i can see, the breaking change was introduced in MPLAB X 4.20 (most likely for XC8 2.00).
I am working on the needed change.

**Comment by mellexpro** [comment]
Thanks, your effort is much appreciated, I will test it as soon as fix goes live.

**Comment by mellexpro** [comment]
Any progress on the fix?

**Comment by mc6pac** [comment]
Sorry for the delay. 
I have a fix now, and I will create a new release shortly.

**Comment by mc6pac** [comment]
NBM file sent to Microchip. An update should be available in MPLAB X soon.
